api = "0.2"

[buildpack]
  id = "org.cloudfoundry.bundler"
  name = "Bundler Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    bundler = "2.x.x"

  [[metadata.dependencies]]
    id = "bundler"
    name ="Bundler"
    version = "2.1.4"
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler-2.1.4-any-stack-df7bed89.tgz"
    sha256 = "df7bed898d3de06ddeee32f1df71a25a86e653587c13245dfd0b0e006098be79"
    source = "https://github.com/bundler/bundler/tree/v2.1.4"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    source_sha256 = "50014d21d6712079da4d6464de12bb93c278f87c9200d0b60ba99f32c25af489"

  [[metadata.dependencies]]
    id = "bundler"
    name ="Bundler"
    version = "1.17.3"
    uri = "https://buildpacks.cloudfoundry.org/dependencies/bundler/bundler-1.17.3-any-stack-b7502506.tgz"
    sha256 = "b7502506bb8ab5312d4efa208d39dca4a5830762ba6b4b094a72e9aa69702341"
    source = "http://github.com/bundler/bundler/tree/v1.17.3"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    source_sha256 = "a34cf18749cc92e25329fc11418bf7800853b74e1e39f82223841114d84d58de"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
